% *************************************************************************
% WARNING:
% THIS FUNCTION IS INTERNAL TO THE OLFACTOMETER IMPLEMENTATION AND
% SHOULD NOT BE CALLED BY OUTSIDE CODE
% *************************************************************************
% Just returns a structure that contains only the fields that we
% have and do not need to do network query to get
function out = buildEmptyStruct_INTERNAL(obj)
    out = struct( ...
       'RemoteHost', obj.host, ...
       'RemotePort', obj.port, ...
       'RemoteName', obj.name, ...
       'RemoteDescription', obj.description, ...
       'Mixes', {GetMixNames(obj)}, ...       
       'Banks', {GetBankNames(obj)}, ...
       'BankOdorTables', [], ...
       'BankNumOdors', [], ...
       'BankFlowRates', [], ...
       'MixFlowRates', [], ...
       'BankCurrentOdors', [], ...
       'MixBanks', [], ...
       'MixRatios', [], ...
       'MixCarrierFlows', [], ...
       'MixOdorFlows', [], ...
       'BanksEnabled', [] ...
       );
    
    % Must sort fields of structure
    firstfields = fieldnames(out);
    [sorted, ind] = sort(lower(firstfields));
    out = orderfields(out, ind);
